version: '3.7'

services:
    springproject:
        build: 
            context: .
            dockerfile: Dockerfile
            args:
                WAR_FILE: build/libs/springproject-0.0.1-SNAPSHOT.war
        image: bhsbhs235/springproject:0.1
        image: bhsbhs235/springproject:0.1
        ports: 
            - "8081:8080"
        container_name: springproject_green
 